spring:
  redis:
    # Redis服务器地址
    host: 192.168.137.88
    # Redis服务器连接端口
    port: 6379
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
    # redis集群(搭建教程连接：https://blog.csdn.net/hopelgl/article/details/103453799)
#    cluster:
#      max-redirects: 3 # 获取失败 最大重定向次数
#      nodes:
#        - 192.168.33.88:7001
#        - 192.168.33.88:7002
#        - 192.168.33.88:7003
#        - 192.168.33.88:7004
#        - 192.168.33.88:7005
#        - 192.168.33.88:7006