zookeeper:
  address: 192.168.137.88:2181,192.168.137.88:2182,192.168.137.88:2183
  timeout: 1000
dubbo:
  registry:
    address: zookeeper://192.168.137.88:2181
  application:
    name: dubbo-provider
  protocol:
    port: 20880
    name: dubbo
  scan:
    base-packages: liu.hope.zookeeper2181.serviceImpl
server:
  port: 8888
